(eval-when-compile    (require 'color-theme))
(defun color-theme-yoones ()
  "Color theme by Younes SERRAJ, created 2016-01-20."
  (interactive)
  (color-theme-install
   '(color-theme-yoones
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "blue")
      (cursor-color . "red")
      (foreground-color . "white")
      (mouse-color . "black"))
     ((list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (list-matching-lines-prefix-face . shadow)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (bold ((t (:bold t :background "black" :foreground "white" :underline t :weight bold))))
     (bold-italic ((t (:italic t :bold t :foreground "white" :underline t :slant italic :weight bold))))
     (border ((t (:background "blue"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (c-annotation-face ((t (:foreground "magenta"))))
     (c-nonbreakable-space-face ((t (:background "magenta"))))
     (calendar-today-face ((t (:underline t))))
     (completions-annotations ((t (:italic t :slant italic :underline t :background "red"))))
     (completions-common-part ((t (nil))))
     (completions-first-difference ((t (:bold t :weight bold :underline t :foreground "white" :background "black"))))
     (cursor ((t (:background "red"))))
     (diary-face ((t (:foreground "red"))))
     (error ((t (:foreground "#d54e53"))))
     (escape-glyph ((t (:foreground "cyan"))))
     (file-name-shadow ((t (:foreground "#969896"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (font-lock-builtin-face ((t (:foreground "blue"))))
     (font-lock-comment-delimiter-face ((t (:italic t :foreground "#969896" :slant italic))))
     (font-lock-comment-face ((t (:italic t :foreground "cyan" :slant italic))))
     (font-lock-constant-face ((t (:foreground "magenta"))))
     (font-lock-doc-face ((t (:foreground "#969896"))))
     (font-lock-function-name-face ((t (:foreground "cyan"))))
     (font-lock-keyword-face ((t (:foreground "red"))))
     (font-lock-negation-char-face ((t (:foreground "#b9ca4a"))))
     (font-lock-preprocessor-face ((t (:foreground "#c397d8"))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#e7c547"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "#c397d8"))))
     (font-lock-string-face ((t (:foreground "green"))))
     (font-lock-type-face ((t (:foreground "yellow"))))
     (font-lock-variable-name-face ((t (:foreground "blue"))))
     (font-lock-warning-face ((t (:bold t :foreground "magenta" :weight bold))))
     (fringe ((t (:background "#2a2a2a"))))
     (glyphless-char ((t (:underline t))))
     (header-line ((t (:background "#424242" :foreground "#c397d8"))))
     (help-argument-name ((t (:italic t :slant italic :underline t :background "red"))))
     (highlight ((t (:background "blue" :foreground "yellow"))))
     (holiday-face ((t (:background "cyan"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic))))
     (info-header-xref ((t (:bold t :weight bold))))
     (info-index-match ((t (:background "#7aa6da" :foreground "#000000"))))
     (info-menu-header ((t (:bold t :underline t :weight bold))))
     (info-menu-star ((t (:foreground "red1" :underline t))))
     (info-node ((t (:italic t :bold t :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :foreground "yellow" :weight bold))))
     (info-title-2 ((t (:bold t :foreground "lightblue" :weight bold))))
     (info-title-3 ((t (:bold t :weight bold))))
     (info-title-4 ((t (:bold t :weight bold))))
     (info-xref ((t (:bold t :weight bold))))
     (info-xref-visited ((t (:foreground "#c397d8"))))
     (isearch ((t (:foreground "#000000" :background "#e7c547"))))
     (isearch-fail ((t (:bold t :weight bold :background "magenta" :foreground "#000000"))))
     (italic ((t (:italic t :background "red" :underline t :slant italic))))
     (lazy-highlight ((t (:foreground "#000000" :background "#70c0b1"))))
     (link ((t (:underline t))))
     (link-visited ((t (:foreground "#c397d8"))))
     (match ((t (:foreground "#000000" :background "#7aa6da"))))
     ;; (menu ((t (:background "#2a2a2a"))))
     (menu ((t (:background "yellow" :foreground "#000000"))))
     (message-cited-text ((t (:foreground "LightPink1"))))
     (message-cited-text-face ((t (:foreground "LightPink1"))))
     (message-header-cc ((t (:bold t :weight bold :foreground "#e78c45"))))
     (message-header-cc-face ((t (:bold t :weight bold :foreground "#e78c45"))))
     (message-header-name ((t (:foreground "#7aa6da"))))
     (message-header-name-face ((t (:foreground "#7aa6da"))))
     (message-header-newsgroups ((t (:foreground "#70c0b1" :slant normal))))
     (message-header-newsgroups-face ((t (:foreground "#70c0b1" :slant normal))))
     (message-header-other ((t (:weight normal))))
     (message-header-other-face ((t (:weight normal))))
     (message-header-subject ((t (:bold t :foreground "#e7c547" :weight bold))))
     (message-header-subject-face ((t (:bold t :foreground "#e7c547" :weight bold))))
     (message-header-to ((t (:bold t :foreground "#e78c45" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "#e78c45" :weight bold))))
     (message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
     (message-header-xheader-face ((t (:foreground "DeepSkyBlue1"))))
     (message-mml ((t (:foreground "MediumSpringGreen"))))
     (message-mml-face ((t (:foreground "MediumSpringGreen"))))
     (message-separator ((t (:foreground "#c397d8"))))
     (message-separator-face ((t (:foreground "#c397d8"))))
     (minibuffer-prompt ((t (:foreground "#7aa6da"))))
     (mm-command-output ((t (:foreground "ForestGreen"))))
     (mode-line ((t (:background "#424242" :foreground "#eaeaea"))))
     (mode-line-buffer-id ((t (:background "white" :foreground "red"))))
     (mode-line-emphasis ((t (:italic t :foreground "#eaeaea" :slant italic))))
     (mode-line-highlight ((t (:bold t :foreground "#c397d8" :box nil :weight bold))))
     (mode-line-inactive ((t (:background "#2a2a2a" :foreground "#eaeaea"))))
     (modeline ((t (:background "white" :foreground "blue"))))
     (modeline-mousable ((t (:background "white" :foreground "magenta"))))
     (modeline-mousable-minor-mode ((t (:background "white" :foreground "yellow"))))
     (mouse ((t (:background "black"))))
     (next-error ((t (:foreground "black" :background "white"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (pp^L-highlight ((t (nil))))
     (query-replace ((t (:background "#e7c547" :foreground "#000000"))))
     (region ((t (:background "white" :foreground "black"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "blue"))))
     (shadow ((t (:foreground "#969896"))))
     (show-paren-match ((t (:background "red" :foreground "#2a2a2a"))))
     (show-paren-mismatch ((t (:background "magenta" :foreground "white"))))
     (success ((t (:foreground "#b9ca4a"))))
     (tool-bar ((t (:foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "#d54e53" :foreground "#e7c547"))))
     (tty-menu-disabled-face ((t (:background "blue" :foreground "lightgray"))))
     (tty-menu-enabled-face ((t (:bold t :background "blue" :foreground "yellow" :weight bold))))
     (tty-menu-selected-face ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (:foreground "#eaeaea" :background "#2a2a2a"))))
     (warning ((t (:foreground "#e78c45"))))
     (widget-button ((t (:underline t))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "#2a2a2a" :box (:line-width 1 :color "#eaeaea")))))
     (widget-inactive ((t (:foreground "#969896"))))
     (widget-single-line-field ((t (:background "green3" :foreground "black"))))
     (window-divider ((t (:foreground "gray60"))))
     (window-divider-first-pixel ((t (:foreground "gray80"))))
     (window-divider-last-pixel ((t (:foreground "gray40"))))
     (zmacs-region ((t (:background "cyan" :foreground "black")))))))
(add-to-list 'color-themes '(color-theme-yoones  "yoones" "Younes Serraj"))
