#!/bin/bash

alias l='ls'
alias ll='ls -l'
alias lla='ll -a'
alias lld='ll -d * | grep ^d'
alias llh='ll -h'
alias llah='ll -ah'
alias clean='rm -f *~ ; rm -f .*~ ; rm -f \#*\#'
alias ccl='clean ; clear ; pwd ; ll'
alias sne='sudo emacs -nw'
alias df='df -h'
alias j='jobs'
alias catx='hexdump -C'
alias h='hexdump -C'
alias bc="\bc -q"
alias m="most"
alias pg='ping -c 1 google.com'
alias wif="watch ifconfig"
alias rgrep="grep -r"
alias rigrep="grep -ri"
alias gri="grep -ri"
# alias ne='emacs -nw'
alias cdiff="colordiff"

function ne()
{
    nb_lines=$(echo "$1" | tr ':' '\n' | wc -l | tr -d '\n')
    if [ "$nb_lines" == "2" ]; then
	filename=$(echo -n "$1" | cut -d ':' -f 1)
	line=$(echo -n "$1" | cut -d ':' -f 2)
	emacs -nw "+$line" "$filename"
    else
	emacs -nw "$1"
    fi
}
