#!/bin/bash

alias ner='ne ./config/routes.rb'

alias rs='rails s'
alias rc='rails c'
alias rr="rrout"
alias migrate="bundle exec rake db:migrate"

alias goc="gor app/controllers"
alias gom="gor app/models"
alias gov="gor app/views"
alias goa="gor app/assets"
alias goaj="gor app/assets/javascripts"
alias goas="gor app/assets/stylesheets"
alias gos="gor app/services"
alias got="gor app/transactions"
alias gow="gor app/workers"
alias gol="gor config/locales"

alias gosp="gor spec"
alias gosps="gor spec/services"
alias gospt="gor spec/transactions"
alias gospc="gor spec/controllers"
alias gospm="gor spec/models"
alias gospf="gor spec/factories"

alias be="bundle exec"
alias be.test="RAILS_ENV=test bundle exec"
alias dk.test="RAILS_ENV=test docker-compose"

function rd()
{
    grep -e '^[ ]*describe' -e '^[ ]*context' -e '^[ ]*it' $@ | sed 's/ do$//g'
}

function gotogem()
{
    cd `gem which $1 | rev | cut -d '/' -f 2- | rev`
}

function gor()
{
    # 1) Rails app
    # 2) Git repository
    path=`find_rails_app_root.rb`
    if [ "$?" != "0" ]; then
	git rev-parse --git-dir > /dev/null 2> /dev/null
	if [ "$?" == "0" ]; then
	    path="$(git rev-parse --git-dir)/.."
	else
	    echo "Error: no rails app nor git repository found" > /dev/stderr
	    return 1
	fi
    fi
    if [ "$1" != "" ]; then
	path=`solve_path.rb $path $@`
	if [ "$?" != "0" ]; then
	    echo "Error: subpath not found"
	    return 1
	fi
    fi
    cd $path
}

function gotogems()
{
    path=`find_ruby_gems.rb`
    if [ "$?" == "0" ]; then
	cd $path
	return 0
    else
	echo "Error: folder found" > /dev/stderr
	return 1
    fi
}

function rrout()
{
    rake routes | grep "$1"
}

function reset_db()
{
    path=`find_rails_app_root.rb`
    if [ "$?" == "0" ]; then
	rm -f "$path/db/development.sqlite3"
	rm -f "$path/db/test.sqlite3"
	bundle exec rake db:create
	bundle exec rake db:migrate
	bundle exec rake db:seed
	return 0
    else
	echo "Error: no rails app found" > /dev/stderr
	return 1
    fi
}

function reset_test_db()
{
    path=`find_rails_app_root.rb`
    if [ "$?" == "0" ]; then
	rake.test db:drop
	rake.test db:create
	rake.test db:migrate
	return 0
    else
	echo "Error: no rails app found" > /dev/stderr
	return 1
    fi
}

function rlm()
{
    # rails list models

    previous_pwd=$OLD_PWD
    current_pwd=$(pwd)
    gom || return 1
    if [ "$1" == "" ]; then
	ls | sed "s/^/  /g"
    else
	ls | sed "s/^/  /g" | grep "$1"
    fi
    cd "$current_pwd"
    export OLD_PWD="$previous_pwd"
}

function rlm_complete()
{
    rlm $@ | sed "s/^  //g" | sed 's/\.rb$//g'
}

function rspec-doc()
{
    rspec $@ --dry-run --format documentation
}

function dbdesc()
{
    path=`find_rails_app_root.rb`
    if [ "$?" == "0" ]; then
	_dbdesc "$path/db/schema.rb" $@
	return 0
    else
	echo "Error: no rails app found" > /dev/stderr
	return 1
    fi
}

function rspecit()
{
    alias x="clear ; rspec '$1'"
    alias n="emacs -nw '$1'"
}

function gc()
{
    cd $(pwd | sed 's/\/spec\//\/app\//g')
}

function gs()
{
    cd $(pwd | sed 's/\/app\//\/spec\//g')
}
