#!/bin/bash

alias ner='ne ./config/routes.rb'
alias rs='rails s'
alias rc='rails c'
alias rr="rrout"
alias migrate="rake db:migrate"
alias goc="gor && cd app/controllers"
alias gom="gor && cd app/models"
alias gov="gor && cd app/views"
alias goa="gor && cd app/assets"
alias gos="gor && cd app/services"
alias gosp="gor && cd spec"
alias gow="gor && cd app/workers"

function gotogem()
{
    cd `gem which $1 | rev | cut -d '/' -f 2- | rev`
}

function gor()
{
    path=`find_rails_app_root.rb`
    if [ "$?" == "0" ]; then
	cd $path
	return 0
    else
	echo "Error: no rails app found" > /dev/stderr
	return 1
    fi
}

function gogems()
{
    path=`find_ruby_gems.rb`
    if [ "$?" == "0" ]; then
	cd $path
	return 0
    else
	echo "Error: folder found" > /dev/stderr
	return 1
    fi
}

function rrout()
{
    rake routes | grep "$1"
}

function reset_db()
{
    path=`find_rails_app_root.rb`
    if [ "$?" == "0" ]; then
	rm -f "$path/db/development.sqlite3"
	rm -f "$path/db/test.sqlite3"
	rake db:create
	rake db:migrate
	rake db:seed
	return 0
    else
	echo "Error: no rails app found" > /dev/stderr
	return 1
    fi
}

function rlm()
{
    # rails list models

    previous_pwd=$OLD_PWD
    current_pwd=$(pwd)
    gom || return 1
    ls | sed "s/^/  /g"
    cd "$current_pwd"
    export OLD_PWD="$previous_pwd"
}

function rspec-doc()
{
    rspec $@ --dry-run --format documentation
}
