#!/bin/bash

alias gotmp="cd /tmp/toto"

current_gop_file="$HOME/.gop"
function setgop()
{
    echo `pwd` > $current_gop_file
    export P=`pwd`
}
alias setp="setgop"

function gop()
{
    if [ -f "$HOME/.gop" ]; then
	cd -- "`cat $current_gop_file`"
    else
	cd $HOME/projects
    fi
    export P=`pwd`
}

export P=`cat $current_gop_file`
